import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";

import { cn } from "@/helpers/cn";

const poppins = Poppins({
  style: 'normal',
  weight: '400',
  subsets: ['latin'],
}) 

export const metadata: Metadata = {
  title: "A little of charity",
  description: "Generated by @jucileycostaweb3",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("", poppins.className)}>
        <div>
          {children}  
        </div>
      </body>
    </html>
  );
}
